spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/itshop-db
    username: itshop
    password: S3cret
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/liquibase/db-changelog.xml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB